### ISSUE TITLE
About downloading data

### ISSUE THREAD

**Issue by den6** [maxischuh/TwinBooster#1]
Hi, maxischuh

When I executed the command below to download the data and barlow_twins model, the following error was output.

```
root@dc59d39a7124:~/TwinBooster/src/twinbooster#` git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/maxischuh/TwinBooster.git/info/lfs'
```

Is it possible to provide data in a different way?

Best Regards,
den6

**Comment by den6** [comment]
I would appreciate it if you could let me know the status of this matter.

**Comment by maxischuh** [comment]
Hi, I have implemented a new way to download the models, it is already live on PyPI. 
Install the package with `pip install twinbooster`. Then you can download the pre-trained models with `twinbooster.download_models()`.

I have previously encountered file size limitations on GitHub, PyPI, etc. I hope this solves your problem.

**Comment by den6** [comment]
Hi, maxischuh

Thank you for your update.

But I  think, the model download URL is incorrect.
In downloader.py, You need to change getlink → dl.

And, the download url currently returns a 404 error.
It was available for download during the day. It's night in Japan now.
I would appreciate it if you could check it out.

Best Regards,
den6

**Comment by maxischuh** [comment]
Hi, I had the same problem, but it is fixed now :)

**Comment by den6** [comment]
Hi, maxischuh

According to syncandshare's guidelines, it is only available to persons affiliated with German universities.
However, it also states that there is an option to grant access to external users.
If this is possible, could you please confirm the setting?

Best Regards,
den6
