### ISSUE TITLE
Download URL

### ISSUE THREAD

**Issue by den6** [maxischuh/TwinBooster#2]
Hi, maxischuh

I've opened a new issue.

Thank you for your update.

But I think, the model download URL in downloader.py is incorrect, you need to change getlink → dl.

And, the download url currently returns a 404 error.
It was available for download for a few days.
I would appreciate it if you could check it out.

Best Regards,
den6

**Comment by maxischuh** [comment]
The institute revoked the links, I need to check why. Kind regards, Maxi

**Comment by maxischuh** [comment]
It should work now. Lets hope it stays that way.

**Comment by den6** [comment]
Hi, maxischuh

Thank you for resolving this issue.I was able to download them successfully.

Best Regards,
den6
